// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/micro/auth/auth.proto

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	proto/micro/auth/auth.proto

It has these top-level messages:
	CreateSessionRequest
	CreateSessionResponse
	ValidateTokenRequest
	ValidateTokenResponse
	DeleteSessionRequest
	DeleteSessionResponse
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Auth service

type AuthService interface {
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...client.CallOption) (*CreateSessionResponse, error)
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...client.CallOption) (*ValidateTokenResponse, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...client.CallOption) (*DeleteSessionResponse, error)
}

type authService struct {
	c    client.Client
	name string
}

func NewAuthService(name string, c client.Client) AuthService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "auth"
	}
	return &authService{
		c:    c,
		name: name,
	}
}

func (c *authService) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...client.CallOption) (*CreateSessionResponse, error) {
	req := c.c.NewRequest(c.name, "Auth.CreateSession", in)
	out := new(CreateSessionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...client.CallOption) (*ValidateTokenResponse, error) {
	req := c.c.NewRequest(c.name, "Auth.ValidateToken", in)
	out := new(ValidateTokenResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...client.CallOption) (*DeleteSessionResponse, error) {
	req := c.c.NewRequest(c.name, "Auth.DeleteSession", in)
	out := new(DeleteSessionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthHandler interface {
	CreateSession(context.Context, *CreateSessionRequest, *CreateSessionResponse) error
	ValidateToken(context.Context, *ValidateTokenRequest, *ValidateTokenResponse) error
	DeleteSession(context.Context, *DeleteSessionRequest, *DeleteSessionResponse) error
}

func RegisterAuthHandler(s server.Server, hdlr AuthHandler, opts ...server.HandlerOption) {
	type auth interface {
		CreateSession(ctx context.Context, in *CreateSessionRequest, out *CreateSessionResponse) error
		ValidateToken(ctx context.Context, in *ValidateTokenRequest, out *ValidateTokenResponse) error
		DeleteSession(ctx context.Context, in *DeleteSessionRequest, out *DeleteSessionResponse) error
	}
	type Auth struct {
		auth
	}
	h := &authHandler{hdlr}
	s.Handle(s.NewHandler(&Auth{h}, opts...))
}

type authHandler struct {
	AuthHandler
}

func (h *authHandler) CreateSession(ctx context.Context, in *CreateSessionRequest, out *CreateSessionResponse) error {
	return h.AuthHandler.CreateSession(ctx, in, out)
}

func (h *authHandler) ValidateToken(ctx context.Context, in *ValidateTokenRequest, out *ValidateTokenResponse) error {
	return h.AuthHandler.ValidateToken(ctx, in, out)
}

func (h *authHandler) DeleteSession(ctx context.Context, in *DeleteSessionRequest, out *DeleteSessionResponse) error {
	return h.AuthHandler.DeleteSession(ctx, in, out)
}
